version: '2'

services:
  traefik:
    image: traefik:1.5-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web-gateway
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik.toml:/traefik.toml"
      - "./acme.json:/acme.json"

networks:
  web-gateway:
    external: true
